//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeNavredi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookkeeperBill
    {
        public int Id { get; set; }
        public int BookkeeperId { get; set; }
        public int OrganisationId { get; set; }
    
        public virtual Bookkeeper Bookkeeper { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
