//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeNavredi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronomic { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PassportNumber { get; set; }
        public string PassportSerial { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Guid { get; set; }
        public string Ein { get; set; }
        public string SocialSecNumber { get; set; }
        public Nullable<int> SecialSecTypeId { get; set; }
        public string IpAddress { get; set; }
        public string Ua { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual SocialSecType SocialSecType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
