//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeNavredi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompleteService
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime date { get; set; }
        public int UserId { get; set; }
        public int RecyclerWorkId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual RecyclerWork RecyclerWork { get; set; }
        public virtual Service Service { get; set; }
    }
}
