//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeNavredi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeNavrediEntities : DbContext
    {
        public NeNavrediEntities()
            : base("name=NeNavrediEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Bookkeeper> Bookkeeper { get; set; }
        public virtual DbSet<BookkeeperBill> BookkeeperBill { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CompleteService> CompleteService { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EnterHistory> EnterHistory { get; set; }
        public virtual DbSet<ExplorerEmployee> ExplorerEmployee { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderService> OrderService { get; set; }
        public virtual DbSet<Organisation> Organisation { get; set; }
        public virtual DbSet<Recycler> Recycler { get; set; }
        public virtual DbSet<RecyclerWork> RecyclerWork { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<SocialSecType> SocialSecType { get; set; }
        public virtual DbSet<StatusId> StatusId { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserService> UserService { get; set; }
    }
}
